import ClassicalProblemsSchubertCalculusTheoremCanonicalLaneLean.GrassmannianVariety
import ClassicalProblemsSchubertCalculusTheoremCanonicalLaneLean.SchubertConditions
import ClassicalProblemsSchubertCalculusTheoremCanonicalLaneLean.SchubertCalculusBridge
import ClassicalProblemsSchubertCalculusTheoremCanonicalLaneLean.SchubertCalculusGate
import ClassicalProblemsSchubertCalculusTheoremCanonicalLaneLean.FinalTheorem

end ClassicalProblemsSchubertCalculusTheoremCanonicalLaneLean
end HautevilleHouse